/*
 * This file is part of the MicroPython project, http://micropython.org/
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2013-2019 Damien P. George
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
// CIRCUITPY-CHANGE: generated by devtools/archive/zbwork/gen_multi.py. One entry
// per value of the three MULTI opcodes, so that the operand is an immediate in
// the handler instead of being recovered from the opcode byte at run time.
// Only used with computed goto; the switch-based dispatch keeps the shared
// handlers, which it reaches through its default case.
// *FORMAT-OFF*
                ENTRY(MP_BC_LOAD_FAST_MULTI_0):
                    obj_shared = fastn[-0];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_1):
                    obj_shared = fastn[-1];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_2):
                    obj_shared = fastn[-2];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_3):
                    obj_shared = fastn[-3];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_4):
                    obj_shared = fastn[-4];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_5):
                    obj_shared = fastn[-5];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_6):
                    obj_shared = fastn[-6];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_7):
                    obj_shared = fastn[-7];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_8):
                    obj_shared = fastn[-8];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_9):
                    obj_shared = fastn[-9];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_10):
                    obj_shared = fastn[-10];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_11):
                    obj_shared = fastn[-11];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_12):
                    obj_shared = fastn[-12];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_13):
                    obj_shared = fastn[-13];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_14):
                    obj_shared = fastn[-14];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_15):
                    obj_shared = fastn[-15];
                    goto load_check;

                ENTRY(MP_BC_STORE_FAST_MULTI_0):
                    fastn[-0] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_1):
                    fastn[-1] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_2):
                    fastn[-2] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_3):
                    fastn[-3] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_4):
                    fastn[-4] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_5):
                    fastn[-5] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_6):
                    fastn[-6] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_7):
                    fastn[-7] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_8):
                    fastn[-8] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_9):
                    fastn[-9] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_10):
                    fastn[-10] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_11):
                    fastn[-11] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_12):
                    fastn[-12] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_13):
                    fastn[-13] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_14):
                    fastn[-14] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_15):
                    fastn[-15] = POP();
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_0):
                    PUSH(MP_OBJ_NEW_SMALL_INT(0 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_1):
                    PUSH(MP_OBJ_NEW_SMALL_INT(1 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_2):
                    PUSH(MP_OBJ_NEW_SMALL_INT(2 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_3):
                    PUSH(MP_OBJ_NEW_SMALL_INT(3 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_4):
                    PUSH(MP_OBJ_NEW_SMALL_INT(4 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_5):
                    PUSH(MP_OBJ_NEW_SMALL_INT(5 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_6):
                    PUSH(MP_OBJ_NEW_SMALL_INT(6 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_7):
                    PUSH(MP_OBJ_NEW_SMALL_INT(7 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_8):
                    PUSH(MP_OBJ_NEW_SMALL_INT(8 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_9):
                    PUSH(MP_OBJ_NEW_SMALL_INT(9 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_10):
                    PUSH(MP_OBJ_NEW_SMALL_INT(10 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_11):
                    PUSH(MP_OBJ_NEW_SMALL_INT(11 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_12):
                    PUSH(MP_OBJ_NEW_SMALL_INT(12 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_13):
                    PUSH(MP_OBJ_NEW_SMALL_INT(13 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_14):
                    PUSH(MP_OBJ_NEW_SMALL_INT(14 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_15):
                    PUSH(MP_OBJ_NEW_SMALL_INT(15 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_16):
                    PUSH(MP_OBJ_NEW_SMALL_INT(16 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_17):
                    PUSH(MP_OBJ_NEW_SMALL_INT(17 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_18):
                    PUSH(MP_OBJ_NEW_SMALL_INT(18 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_19):
                    PUSH(MP_OBJ_NEW_SMALL_INT(19 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_20):
                    PUSH(MP_OBJ_NEW_SMALL_INT(20 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_21):
                    PUSH(MP_OBJ_NEW_SMALL_INT(21 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_22):
                    PUSH(MP_OBJ_NEW_SMALL_INT(22 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_23):
                    PUSH(MP_OBJ_NEW_SMALL_INT(23 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_24):
                    PUSH(MP_OBJ_NEW_SMALL_INT(24 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_25):
                    PUSH(MP_OBJ_NEW_SMALL_INT(25 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_26):
                    PUSH(MP_OBJ_NEW_SMALL_INT(26 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_27):
                    PUSH(MP_OBJ_NEW_SMALL_INT(27 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_28):
                    PUSH(MP_OBJ_NEW_SMALL_INT(28 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_29):
                    PUSH(MP_OBJ_NEW_SMALL_INT(29 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_30):
                    PUSH(MP_OBJ_NEW_SMALL_INT(30 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_31):
                    PUSH(MP_OBJ_NEW_SMALL_INT(31 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_32):
                    PUSH(MP_OBJ_NEW_SMALL_INT(32 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_33):
                    PUSH(MP_OBJ_NEW_SMALL_INT(33 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_34):
                    PUSH(MP_OBJ_NEW_SMALL_INT(34 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_35):
                    PUSH(MP_OBJ_NEW_SMALL_INT(35 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_36):
                    PUSH(MP_OBJ_NEW_SMALL_INT(36 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_37):
                    PUSH(MP_OBJ_NEW_SMALL_INT(37 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_38):
                    PUSH(MP_OBJ_NEW_SMALL_INT(38 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_39):
                    PUSH(MP_OBJ_NEW_SMALL_INT(39 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_40):
                    PUSH(MP_OBJ_NEW_SMALL_INT(40 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_41):
                    PUSH(MP_OBJ_NEW_SMALL_INT(41 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_42):
                    PUSH(MP_OBJ_NEW_SMALL_INT(42 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_43):
                    PUSH(MP_OBJ_NEW_SMALL_INT(43 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_44):
                    PUSH(MP_OBJ_NEW_SMALL_INT(44 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_45):
                    PUSH(MP_OBJ_NEW_SMALL_INT(45 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_46):
                    PUSH(MP_OBJ_NEW_SMALL_INT(46 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_47):
                    PUSH(MP_OBJ_NEW_SMALL_INT(47 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_48):
                    PUSH(MP_OBJ_NEW_SMALL_INT(48 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_49):
                    PUSH(MP_OBJ_NEW_SMALL_INT(49 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_50):
                    PUSH(MP_OBJ_NEW_SMALL_INT(50 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_51):
                    PUSH(MP_OBJ_NEW_SMALL_INT(51 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_52):
                    PUSH(MP_OBJ_NEW_SMALL_INT(52 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_53):
                    PUSH(MP_OBJ_NEW_SMALL_INT(53 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_54):
                    PUSH(MP_OBJ_NEW_SMALL_INT(54 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_55):
                    PUSH(MP_OBJ_NEW_SMALL_INT(55 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_56):
                    PUSH(MP_OBJ_NEW_SMALL_INT(56 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_57):
                    PUSH(MP_OBJ_NEW_SMALL_INT(57 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_58):
                    PUSH(MP_OBJ_NEW_SMALL_INT(58 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_59):
                    PUSH(MP_OBJ_NEW_SMALL_INT(59 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_60):
                    PUSH(MP_OBJ_NEW_SMALL_INT(60 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_61):
                    PUSH(MP_OBJ_NEW_SMALL_INT(61 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_62):
                    PUSH(MP_OBJ_NEW_SMALL_INT(62 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_63):
                    PUSH(MP_OBJ_NEW_SMALL_INT(63 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

