/*
 * This file is part of the MicroPython project, http://micropython.org/
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2013-2019 Damien P. George
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
// CIRCUITPY-CHANGE: generated by devtools/archive/zbwork/gen_multi2.py. One entry
// per value of every MULTI opcode, so that the operand -- a local's index, a
// constant, an operator -- is a compile-time constant in the handler instead of
// being recovered from the opcode byte at run time. Only used with computed goto;
// the switch-based dispatch keeps the shared handlers, which it reaches through
// its default case.
// *FORMAT-OFF*
                ENTRY(MP_BC_LOAD_FAST_MULTI_0):
                    obj_shared = fastn[-0];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_1):
                    obj_shared = fastn[-1];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_2):
                    obj_shared = fastn[-2];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_3):
                    obj_shared = fastn[-3];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_4):
                    obj_shared = fastn[-4];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_5):
                    obj_shared = fastn[-5];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_6):
                    obj_shared = fastn[-6];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_7):
                    obj_shared = fastn[-7];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_8):
                    obj_shared = fastn[-8];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_9):
                    obj_shared = fastn[-9];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_10):
                    obj_shared = fastn[-10];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_11):
                    obj_shared = fastn[-11];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_12):
                    obj_shared = fastn[-12];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_13):
                    obj_shared = fastn[-13];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_14):
                    obj_shared = fastn[-14];
                    goto load_check;

                ENTRY(MP_BC_LOAD_FAST_MULTI_15):
                    obj_shared = fastn[-15];
                    goto load_check;

                ENTRY(MP_BC_STORE_FAST_MULTI_0):
                    fastn[-0] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_1):
                    fastn[-1] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_2):
                    fastn[-2] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_3):
                    fastn[-3] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_4):
                    fastn[-4] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_5):
                    fastn[-5] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_6):
                    fastn[-6] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_7):
                    fastn[-7] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_8):
                    fastn[-8] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_9):
                    fastn[-9] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_10):
                    fastn[-10] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_11):
                    fastn[-11] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_12):
                    fastn[-12] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_13):
                    fastn[-13] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_14):
                    fastn[-14] = POP();
                    DISPATCH();

                ENTRY(MP_BC_STORE_FAST_MULTI_15):
                    fastn[-15] = POP();
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_0):
                    PUSH(MP_OBJ_NEW_SMALL_INT(0 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_1):
                    PUSH(MP_OBJ_NEW_SMALL_INT(1 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_2):
                    PUSH(MP_OBJ_NEW_SMALL_INT(2 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_3):
                    PUSH(MP_OBJ_NEW_SMALL_INT(3 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_4):
                    PUSH(MP_OBJ_NEW_SMALL_INT(4 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_5):
                    PUSH(MP_OBJ_NEW_SMALL_INT(5 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_6):
                    PUSH(MP_OBJ_NEW_SMALL_INT(6 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_7):
                    PUSH(MP_OBJ_NEW_SMALL_INT(7 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_8):
                    PUSH(MP_OBJ_NEW_SMALL_INT(8 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_9):
                    PUSH(MP_OBJ_NEW_SMALL_INT(9 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_10):
                    PUSH(MP_OBJ_NEW_SMALL_INT(10 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_11):
                    PUSH(MP_OBJ_NEW_SMALL_INT(11 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_12):
                    PUSH(MP_OBJ_NEW_SMALL_INT(12 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_13):
                    PUSH(MP_OBJ_NEW_SMALL_INT(13 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_14):
                    PUSH(MP_OBJ_NEW_SMALL_INT(14 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_15):
                    PUSH(MP_OBJ_NEW_SMALL_INT(15 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_16):
                    PUSH(MP_OBJ_NEW_SMALL_INT(16 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_17):
                    PUSH(MP_OBJ_NEW_SMALL_INT(17 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_18):
                    PUSH(MP_OBJ_NEW_SMALL_INT(18 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_19):
                    PUSH(MP_OBJ_NEW_SMALL_INT(19 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_20):
                    PUSH(MP_OBJ_NEW_SMALL_INT(20 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_21):
                    PUSH(MP_OBJ_NEW_SMALL_INT(21 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_22):
                    PUSH(MP_OBJ_NEW_SMALL_INT(22 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_23):
                    PUSH(MP_OBJ_NEW_SMALL_INT(23 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_24):
                    PUSH(MP_OBJ_NEW_SMALL_INT(24 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_25):
                    PUSH(MP_OBJ_NEW_SMALL_INT(25 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_26):
                    PUSH(MP_OBJ_NEW_SMALL_INT(26 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_27):
                    PUSH(MP_OBJ_NEW_SMALL_INT(27 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_28):
                    PUSH(MP_OBJ_NEW_SMALL_INT(28 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_29):
                    PUSH(MP_OBJ_NEW_SMALL_INT(29 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_30):
                    PUSH(MP_OBJ_NEW_SMALL_INT(30 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_31):
                    PUSH(MP_OBJ_NEW_SMALL_INT(31 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_32):
                    PUSH(MP_OBJ_NEW_SMALL_INT(32 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_33):
                    PUSH(MP_OBJ_NEW_SMALL_INT(33 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_34):
                    PUSH(MP_OBJ_NEW_SMALL_INT(34 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_35):
                    PUSH(MP_OBJ_NEW_SMALL_INT(35 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_36):
                    PUSH(MP_OBJ_NEW_SMALL_INT(36 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_37):
                    PUSH(MP_OBJ_NEW_SMALL_INT(37 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_38):
                    PUSH(MP_OBJ_NEW_SMALL_INT(38 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_39):
                    PUSH(MP_OBJ_NEW_SMALL_INT(39 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_40):
                    PUSH(MP_OBJ_NEW_SMALL_INT(40 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_41):
                    PUSH(MP_OBJ_NEW_SMALL_INT(41 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_42):
                    PUSH(MP_OBJ_NEW_SMALL_INT(42 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_43):
                    PUSH(MP_OBJ_NEW_SMALL_INT(43 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_44):
                    PUSH(MP_OBJ_NEW_SMALL_INT(44 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_45):
                    PUSH(MP_OBJ_NEW_SMALL_INT(45 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_46):
                    PUSH(MP_OBJ_NEW_SMALL_INT(46 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_47):
                    PUSH(MP_OBJ_NEW_SMALL_INT(47 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_48):
                    PUSH(MP_OBJ_NEW_SMALL_INT(48 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_49):
                    PUSH(MP_OBJ_NEW_SMALL_INT(49 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_50):
                    PUSH(MP_OBJ_NEW_SMALL_INT(50 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_51):
                    PUSH(MP_OBJ_NEW_SMALL_INT(51 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_52):
                    PUSH(MP_OBJ_NEW_SMALL_INT(52 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_53):
                    PUSH(MP_OBJ_NEW_SMALL_INT(53 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_54):
                    PUSH(MP_OBJ_NEW_SMALL_INT(54 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_55):
                    PUSH(MP_OBJ_NEW_SMALL_INT(55 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_56):
                    PUSH(MP_OBJ_NEW_SMALL_INT(56 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_57):
                    PUSH(MP_OBJ_NEW_SMALL_INT(57 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_58):
                    PUSH(MP_OBJ_NEW_SMALL_INT(58 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_59):
                    PUSH(MP_OBJ_NEW_SMALL_INT(59 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_60):
                    PUSH(MP_OBJ_NEW_SMALL_INT(60 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_61):
                    PUSH(MP_OBJ_NEW_SMALL_INT(61 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_62):
                    PUSH(MP_OBJ_NEW_SMALL_INT(62 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_LOAD_CONST_SMALL_INT_MULTI_63):
                    PUSH(MP_OBJ_NEW_SMALL_INT(63 - MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS));
                    DISPATCH();

                ENTRY(MP_BC_UNARY_OP_MULTI_POSITIVE): {
                    MARK_EXC_IP_SELECTIVE();
                    if (mp_obj_is_small_int(TOP())) { DISPATCH(); }
                    SET_TOP(mp_unary_op(MP_UNARY_OP_POSITIVE, TOP()));
                    DISPATCH();
                }

                ENTRY(MP_BC_UNARY_OP_MULTI_NEGATIVE): {
                    MARK_EXC_IP_SELECTIVE();
                    if (mp_obj_is_small_int(TOP())) {
                        mp_int_t v = -MP_OBJ_SMALL_INT_VALUE(TOP());
                        if (MP_SMALL_INT_FITS(v)) { SET_TOP(MP_OBJ_NEW_SMALL_INT(v)); DISPATCH(); }
                    }
                    SET_TOP(mp_unary_op(MP_UNARY_OP_NEGATIVE, TOP()));
                    DISPATCH();
                }

                ENTRY(MP_BC_UNARY_OP_MULTI_INVERT): {
                    MARK_EXC_IP_SELECTIVE();
                    if (mp_obj_is_small_int(TOP())) {
                        SET_TOP(MP_OBJ_NEW_SMALL_INT(~MP_OBJ_SMALL_INT_VALUE(TOP()))); DISPATCH();
                    }
                    SET_TOP(mp_unary_op(MP_UNARY_OP_INVERT, TOP()));
                    DISPATCH();
                }

                ENTRY(MP_BC_UNARY_OP_MULTI_NOT): {
                    MARK_EXC_IP_SELECTIVE();
                    SET_TOP(vm_is_true(TOP()) ? mp_const_false : mp_const_true);
                    DISPATCH();
                    SET_TOP(mp_unary_op(MP_UNARY_OP_NOT, TOP()));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_LESS): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        SET_TOP(mp_obj_new_bool((mp_int_t)lhs < (mp_int_t)rhs));
                        DISPATCH();
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_LESS, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_MORE): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        SET_TOP(mp_obj_new_bool((mp_int_t)lhs > (mp_int_t)rhs));
                        DISPATCH();
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_MORE, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_EQUAL): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        SET_TOP(mp_obj_new_bool(lhs == rhs));
                        DISPATCH();
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_EQUAL, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_LESS_EQUAL): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        SET_TOP(mp_obj_new_bool((mp_int_t)lhs <= (mp_int_t)rhs));
                        DISPATCH();
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_LESS_EQUAL, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_MORE_EQUAL): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        SET_TOP(mp_obj_new_bool((mp_int_t)lhs >= (mp_int_t)rhs));
                        DISPATCH();
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_MORE_EQUAL, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_NOT_EQUAL): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        SET_TOP(mp_obj_new_bool(lhs != rhs));
                        DISPATCH();
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_NOT_EQUAL, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_IN): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    SET_TOP(mp_binary_op(MP_BINARY_OP_IN, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_IS): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    SET_TOP(mp_binary_op(MP_BINARY_OP_IS, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_EXCEPTION_MATCH): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    SET_TOP(mp_binary_op(MP_BINARY_OP_EXCEPTION_MATCH, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_INPLACE_OR): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        SET_TOP((mp_obj_t)((mp_int_t)lhs | (mp_int_t)rhs));
                        DISPATCH();
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_INPLACE_OR, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_INPLACE_XOR): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        SET_TOP((mp_obj_t)(((mp_int_t)lhs ^ (mp_int_t)rhs) | 1));
                        DISPATCH();
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_INPLACE_XOR, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_INPLACE_AND): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        SET_TOP((mp_obj_t)((mp_int_t)lhs & (mp_int_t)rhs));
                        DISPATCH();
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_INPLACE_AND, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_INPLACE_LSHIFT): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        mp_int_t l = MP_OBJ_SMALL_INT_VALUE(lhs);
                        mp_int_t r = MP_OBJ_SMALL_INT_VALUE(rhs);
                        if (r >= 0 && r < (mp_int_t)(sizeof(mp_int_t) * MP_BITS_PER_BYTE) && l <= (MP_SMALL_INT_MAX >> r) && l >= (MP_SMALL_INT_MIN >> r)) {
                            SET_TOP(MP_OBJ_NEW_SMALL_INT((mp_uint_t)l << r)); DISPATCH();
                        }
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_INPLACE_LSHIFT, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_INPLACE_RSHIFT): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        mp_int_t r = MP_OBJ_SMALL_INT_VALUE(rhs);
                        if (r >= 0 && r < (mp_int_t)(sizeof(mp_int_t) * MP_BITS_PER_BYTE)) {
                            SET_TOP(MP_OBJ_NEW_SMALL_INT(MP_OBJ_SMALL_INT_VALUE(lhs) >> r)); DISPATCH();
                        }
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_INPLACE_RSHIFT, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_INPLACE_ADD): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        mp_int_t v = MP_OBJ_SMALL_INT_VALUE(lhs) + MP_OBJ_SMALL_INT_VALUE(rhs);
                        if (MP_SMALL_INT_FITS(v)) { SET_TOP(MP_OBJ_NEW_SMALL_INT(v)); DISPATCH(); }
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_INPLACE_ADD, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_INPLACE_SUBTRACT): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        mp_int_t v = MP_OBJ_SMALL_INT_VALUE(lhs) - MP_OBJ_SMALL_INT_VALUE(rhs);
                        if (MP_SMALL_INT_FITS(v)) { SET_TOP(MP_OBJ_NEW_SMALL_INT(v)); DISPATCH(); }
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_INPLACE_SUBTRACT, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_INPLACE_MULTIPLY): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        mp_int_t v;
                        if (!mp_mul_mp_int_t_overflow(MP_OBJ_SMALL_INT_VALUE(lhs), MP_OBJ_SMALL_INT_VALUE(rhs), &v) && MP_SMALL_INT_FITS(v)) { SET_TOP(MP_OBJ_NEW_SMALL_INT(v)); DISPATCH(); }
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_INPLACE_MULTIPLY, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_INPLACE_MAT_MULTIPLY): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    SET_TOP(mp_binary_op(MP_BINARY_OP_INPLACE_MAT_MULTIPLY, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_INPLACE_FLOOR_DIVIDE): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        mp_int_t d = MP_OBJ_SMALL_INT_VALUE(rhs);
                        if (d != 0) {
                            mp_int_t v = mp_small_int_floor_divide(MP_OBJ_SMALL_INT_VALUE(lhs), d);
                            if (MP_SMALL_INT_FITS(v)) { SET_TOP(MP_OBJ_NEW_SMALL_INT(v)); DISPATCH(); }
                        }
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_INPLACE_FLOOR_DIVIDE, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_INPLACE_TRUE_DIVIDE): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    SET_TOP(mp_binary_op(MP_BINARY_OP_INPLACE_TRUE_DIVIDE, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_INPLACE_MODULO): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        mp_int_t d = MP_OBJ_SMALL_INT_VALUE(rhs);
                        if (d != 0) {
                            mp_int_t v = mp_small_int_modulo(MP_OBJ_SMALL_INT_VALUE(lhs), d);
                            if (MP_SMALL_INT_FITS(v)) { SET_TOP(MP_OBJ_NEW_SMALL_INT(v)); DISPATCH(); }
                        }
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_INPLACE_MODULO, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_INPLACE_POWER): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    SET_TOP(mp_binary_op(MP_BINARY_OP_INPLACE_POWER, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_OR): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        SET_TOP((mp_obj_t)((mp_int_t)lhs | (mp_int_t)rhs));
                        DISPATCH();
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_OR, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_XOR): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        SET_TOP((mp_obj_t)(((mp_int_t)lhs ^ (mp_int_t)rhs) | 1));
                        DISPATCH();
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_XOR, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_AND): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        SET_TOP((mp_obj_t)((mp_int_t)lhs & (mp_int_t)rhs));
                        DISPATCH();
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_AND, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_LSHIFT): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        mp_int_t l = MP_OBJ_SMALL_INT_VALUE(lhs);
                        mp_int_t r = MP_OBJ_SMALL_INT_VALUE(rhs);
                        if (r >= 0 && r < (mp_int_t)(sizeof(mp_int_t) * MP_BITS_PER_BYTE) && l <= (MP_SMALL_INT_MAX >> r) && l >= (MP_SMALL_INT_MIN >> r)) {
                            SET_TOP(MP_OBJ_NEW_SMALL_INT((mp_uint_t)l << r)); DISPATCH();
                        }
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_LSHIFT, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_RSHIFT): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        mp_int_t r = MP_OBJ_SMALL_INT_VALUE(rhs);
                        if (r >= 0 && r < (mp_int_t)(sizeof(mp_int_t) * MP_BITS_PER_BYTE)) {
                            SET_TOP(MP_OBJ_NEW_SMALL_INT(MP_OBJ_SMALL_INT_VALUE(lhs) >> r)); DISPATCH();
                        }
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_RSHIFT, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_ADD): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        mp_int_t v = MP_OBJ_SMALL_INT_VALUE(lhs) + MP_OBJ_SMALL_INT_VALUE(rhs);
                        if (MP_SMALL_INT_FITS(v)) { SET_TOP(MP_OBJ_NEW_SMALL_INT(v)); DISPATCH(); }
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_ADD, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_SUBTRACT): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        mp_int_t v = MP_OBJ_SMALL_INT_VALUE(lhs) - MP_OBJ_SMALL_INT_VALUE(rhs);
                        if (MP_SMALL_INT_FITS(v)) { SET_TOP(MP_OBJ_NEW_SMALL_INT(v)); DISPATCH(); }
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_SUBTRACT, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_MULTIPLY): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        mp_int_t v;
                        if (!mp_mul_mp_int_t_overflow(MP_OBJ_SMALL_INT_VALUE(lhs), MP_OBJ_SMALL_INT_VALUE(rhs), &v) && MP_SMALL_INT_FITS(v)) { SET_TOP(MP_OBJ_NEW_SMALL_INT(v)); DISPATCH(); }
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_MULTIPLY, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_MAT_MULTIPLY): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    SET_TOP(mp_binary_op(MP_BINARY_OP_MAT_MULTIPLY, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_FLOOR_DIVIDE): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        mp_int_t d = MP_OBJ_SMALL_INT_VALUE(rhs);
                        if (d != 0) {
                            mp_int_t v = mp_small_int_floor_divide(MP_OBJ_SMALL_INT_VALUE(lhs), d);
                            if (MP_SMALL_INT_FITS(v)) { SET_TOP(MP_OBJ_NEW_SMALL_INT(v)); DISPATCH(); }
                        }
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_FLOOR_DIVIDE, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_TRUE_DIVIDE): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    SET_TOP(mp_binary_op(MP_BINARY_OP_TRUE_DIVIDE, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_MODULO): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    if ((((mp_int_t)lhs) & ((mp_int_t)rhs) & 1) != 0) {
                        mp_int_t d = MP_OBJ_SMALL_INT_VALUE(rhs);
                        if (d != 0) {
                            mp_int_t v = mp_small_int_modulo(MP_OBJ_SMALL_INT_VALUE(lhs), d);
                            if (MP_SMALL_INT_FITS(v)) { SET_TOP(MP_OBJ_NEW_SMALL_INT(v)); DISPATCH(); }
                        }
                    }
                    SET_TOP(mp_binary_op(MP_BINARY_OP_MODULO, lhs, rhs));
                    DISPATCH();
                }

                ENTRY(MP_BC_BINARY_OP_MULTI_POWER): {
                    MARK_EXC_IP_SELECTIVE();
                    mp_obj_t rhs = POP();
                    mp_obj_t lhs = TOP();
                    SET_TOP(mp_binary_op(MP_BINARY_OP_POWER, lhs, rhs));
                    DISPATCH();
                }

